# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0930516fbda93bc8f97df1975490c914eefc817737209c35b7b62761c98c561567ecb5691d7a356d50e66f75aa161b9e0b4516d4b705a7b8ac810f9cffc29c8b

test:
  secret_key_base: c9db38910f279ea7cbd8ed0bb8551b62027b4c7fb26ae77727b9378657b1f907f0c9f9bed6c642d37dadbab0814d993ee376030361574537d9694906417a0de6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
